// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.7.0
// source: logicuser.proto

package logicProto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 用户相关
type User struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id       uint64 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Passwd   string `protobuf:"bytes,3,opt,name=passwd,proto3" json:"passwd,omitempty"`
	RePasswd string `protobuf:"bytes,4,opt,name=rePasswd,proto3" json:"rePasswd,omitempty"`
	SkinId   uint32 `protobuf:"varint,5,opt,name=skinId,proto3" json:"skinId,omitempty"`
	Color    *Color `protobuf:"bytes,6,opt,name=color,proto3" json:"color,omitempty"`
}

func (x *User) Reset() {
	*x = User{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logicuser_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_logicuser_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_logicuser_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetPasswd() string {
	if x != nil {
		return x.Passwd
	}
	return ""
}

func (x *User) GetRePasswd() string {
	if x != nil {
		return x.RePasswd
	}
	return ""
}

func (x *User) GetSkinId() uint32 {
	if x != nil {
		return x.SkinId
	}
	return 0
}

func (x *User) GetColor() *Color {
	if x != nil {
		return x.Color
	}
	return nil
}

type UserInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Token      string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Id         uint64 `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	Level      int32  `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`
	Experience int32  `protobuf:"varint,5,opt,name=experience,proto3" json:"experience,omitempty"`
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logicuser_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_logicuser_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_logicuser_proto_rawDescGZIP(), []int{1}
}

func (x *UserInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserInfo) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *UserInfo) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserInfo) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *UserInfo) GetExperience() int32 {
	if x != nil {
		return x.Experience
	}
	return 0
}

// 请求和放回
type Operator struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Operator string `protobuf:"bytes,1,opt,name=operator,proto3" json:"operator,omitempty"`
	Token    string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	User     *User  `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	Room     *Room  `protobuf:"bytes,4,opt,name=room,proto3" json:"room,omitempty"`
	Act      *Act   `protobuf:"bytes,6,opt,name=act,proto3" json:"act,omitempty"`
}

func (x *Operator) Reset() {
	*x = Operator{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logicuser_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Operator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Operator) ProtoMessage() {}

func (x *Operator) ProtoReflect() protoreflect.Message {
	mi := &file_logicuser_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Operator.ProtoReflect.Descriptor instead.
func (*Operator) Descriptor() ([]byte, []int) {
	return file_logicuser_proto_rawDescGZIP(), []int{2}
}

func (x *Operator) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *Operator) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *Operator) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *Operator) GetRoom() *Room {
	if x != nil {
		return x.Room
	}
	return nil
}

func (x *Operator) GetAct() *Act {
	if x != nil {
		return x.Act
	}
	return nil
}

type RequestRoom struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Op   string `protobuf:"bytes,1,opt,name=op,proto3" json:"op,omitempty"`     // "register'、 "update"、 "logoff"、
	Room *Room  `protobuf:"bytes,2,opt,name=room,proto3" json:"room,omitempty"` // 房间信息
}

func (x *RequestRoom) Reset() {
	*x = RequestRoom{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logicuser_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestRoom) ProtoMessage() {}

func (x *RequestRoom) ProtoReflect() protoreflect.Message {
	mi := &file_logicuser_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestRoom.ProtoReflect.Descriptor instead.
func (*RequestRoom) Descriptor() ([]byte, []int) {
	return file_logicuser_proto_rawDescGZIP(), []int{3}
}

func (x *RequestRoom) GetOp() string {
	if x != nil {
		return x.Op
	}
	return ""
}

func (x *RequestRoom) GetRoom() *Room {
	if x != nil {
		return x.Room
	}
	return nil
}

type ResponseRoom struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int32  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Msg    string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Room   *Room  `protobuf:"bytes,3,opt,name=room,proto3" json:"room,omitempty"` // 房间信息
}

func (x *ResponseRoom) Reset() {
	*x = ResponseRoom{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logicuser_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseRoom) ProtoMessage() {}

func (x *ResponseRoom) ProtoReflect() protoreflect.Message {
	mi := &file_logicuser_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseRoom.ProtoReflect.Descriptor instead.
func (*ResponseRoom) Descriptor() ([]byte, []int) {
	return file_logicuser_proto_rawDescGZIP(), []int{4}
}

func (x *ResponseRoom) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ResponseRoom) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ResponseRoom) GetRoom() *Room {
	if x != nil {
		return x.Room
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status   int32     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Msg      string    `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Userinfo *UserInfo `protobuf:"bytes,3,opt,name=userinfo,proto3" json:"userinfo,omitempty"`
	Room     *Room     `protobuf:"bytes,4,opt,name=room,proto3" json:"room,omitempty"`
	UserList []*User   `protobuf:"bytes,5,rep,name=UserList,proto3" json:"UserList,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logicuser_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_logicuser_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_logicuser_proto_rawDescGZIP(), []int{5}
}

func (x *Response) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Response) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *Response) GetUserinfo() *UserInfo {
	if x != nil {
		return x.Userinfo
	}
	return nil
}

func (x *Response) GetRoom() *Room {
	if x != nil {
		return x.Room
	}
	return nil
}

func (x *Response) GetUserList() []*User {
	if x != nil {
		return x.UserList
	}
	return nil
}

type InitResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int32   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Size   int32   `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Msg    string  `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	Player *Ball   `protobuf:"bytes,4,opt,name=player,proto3" json:"player,omitempty"`
	Quark  []*Ball `protobuf:"bytes,5,rep,name=quark,proto3" json:"quark,omitempty"`
}

func (x *InitResponse) Reset() {
	*x = InitResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logicuser_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitResponse) ProtoMessage() {}

func (x *InitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_logicuser_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitResponse.ProtoReflect.Descriptor instead.
func (*InitResponse) Descriptor() ([]byte, []int) {
	return file_logicuser_proto_rawDescGZIP(), []int{6}
}

func (x *InitResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *InitResponse) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *InitResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *InitResponse) GetPlayer() *Ball {
	if x != nil {
		return x.Player
	}
	return nil
}

func (x *InitResponse) GetQuark() []*Ball {
	if x != nil {
		return x.Quark
	}
	return nil
}

type UpdateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  int32      `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Msg     string     `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Players []*Ball    `protobuf:"bytes,3,rep,name=players,proto3" json:"players,omitempty"`
	Foods   []*Ball    `protobuf:"bytes,4,rep,name=foods,proto3" json:"foods,omitempty"`
	Spore   []*Ball    `protobuf:"bytes,5,rep,name=spore,proto3" json:"spore,omitempty"`
	CamPos  *CameraPos `protobuf:"bytes,6,opt,name=camPos,proto3" json:"camPos,omitempty"`
	User    *UserInfo  `protobuf:"bytes,7,opt,name=user,proto3" json:"user,omitempty"`
	Top     *Top       `protobuf:"bytes,8,opt,name=top,proto3" json:"top,omitempty"`
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logicuser_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_logicuser_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_logicuser_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UpdateResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *UpdateResponse) GetPlayers() []*Ball {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *UpdateResponse) GetFoods() []*Ball {
	if x != nil {
		return x.Foods
	}
	return nil
}

func (x *UpdateResponse) GetSpore() []*Ball {
	if x != nil {
		return x.Spore
	}
	return nil
}

func (x *UpdateResponse) GetCamPos() *CameraPos {
	if x != nil {
		return x.CamPos
	}
	return nil
}

func (x *UpdateResponse) GetUser() *UserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *UpdateResponse) GetTop() *Top {
	if x != nil {
		return x.Top
	}
	return nil
}

type Room struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Addr      string  `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	PlayNum   int32   `protobuf:"varint,3,opt,name=playNum,proto3" json:"playNum,omitempty"`
	WaitNum   int32   `protobuf:"varint,4,opt,name=waitNum,proto3" json:"waitNum,omitempty"`
	RobotNum  int32   `protobuf:"varint,5,opt,name=robotNum,proto3" json:"robotNum,omitempty"`
	StartTime int64   `protobuf:"varint,6,opt,name=startTime,proto3" json:"startTime,omitempty"`
	Width     float32 `protobuf:"fixed32,7,opt,name=width,proto3" json:"width,omitempty"`
	Height    float32 `protobuf:"fixed32,8,opt,name=height,proto3" json:"height,omitempty"`
	UserList  []*User `protobuf:"bytes,9,rep,name=userList,proto3" json:"userList,omitempty"`
}

func (x *Room) Reset() {
	*x = Room{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logicuser_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Room) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Room) ProtoMessage() {}

func (x *Room) ProtoReflect() protoreflect.Message {
	mi := &file_logicuser_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Room.ProtoReflect.Descriptor instead.
func (*Room) Descriptor() ([]byte, []int) {
	return file_logicuser_proto_rawDescGZIP(), []int{8}
}

func (x *Room) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Room) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Room) GetPlayNum() int32 {
	if x != nil {
		return x.PlayNum
	}
	return 0
}

func (x *Room) GetWaitNum() int32 {
	if x != nil {
		return x.WaitNum
	}
	return 0
}

func (x *Room) GetRobotNum() int32 {
	if x != nil {
		return x.RobotNum
	}
	return 0
}

func (x *Room) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *Room) GetWidth() float32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Room) GetHeight() float32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Room) GetUserList() []*User {
	if x != nil {
		return x.UserList
	}
	return nil
}

type Act struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type  int32   `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`    // 操作类型 吐袍子，分身
	MoveX float32 `protobuf:"fixed32,2,opt,name=moveX,proto3" json:"moveX,omitempty"` // 方向x
	MoveY float32 `protobuf:"fixed32,3,opt,name=moveY,proto3" json:"moveY,omitempty"` // 方向y
	MoveS float32 `protobuf:"fixed32,4,opt,name=moveS,proto3" json:"moveS,omitempty"` // 速度s
}

func (x *Act) Reset() {
	*x = Act{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logicuser_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Act) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Act) ProtoMessage() {}

func (x *Act) ProtoReflect() protoreflect.Message {
	mi := &file_logicuser_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Act.ProtoReflect.Descriptor instead.
func (*Act) Descriptor() ([]byte, []int) {
	return file_logicuser_proto_rawDescGZIP(), []int{9}
}

func (x *Act) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Act) GetMoveX() float32 {
	if x != nil {
		return x.MoveX
	}
	return 0
}

func (x *Act) GetMoveY() float32 {
	if x != nil {
		return x.MoveY
	}
	return 0
}

func (x *Act) GetMoveS() float32 {
	if x != nil {
		return x.MoveS
	}
	return 0
}

type Ball struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X          float32 `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y          float32 `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Nx         float32 `protobuf:"fixed32,3,opt,name=nx,proto3" json:"nx,omitempty"`
	Ny         float32 `protobuf:"fixed32,4,opt,name=ny,proto3" json:"ny,omitempty"`
	Score      float32 `protobuf:"fixed32,5,opt,name=score,proto3" json:"score,omitempty"`
	Type       uint32  `protobuf:"varint,6,opt,name=type,proto3" json:"type,omitempty"`
	Id         uint32  `protobuf:"varint,7,opt,name=id,proto3" json:"id,omitempty"` //  unity实例的唯一id
	MoveX      float32 `protobuf:"fixed32,8,opt,name=moveX,proto3" json:"moveX,omitempty"`
	MoveY      float32 `protobuf:"fixed32,9,opt,name=moveY,proto3" json:"moveY,omitempty"`
	MoveS      float32 `protobuf:"fixed32,10,opt,name=moveS,proto3" json:"moveS,omitempty"`
	CreateTime int64   `protobuf:"varint,11,opt,name=createTime,proto3" json:"createTime,omitempty"`
	Uid        uint64  `protobuf:"varint,12,opt,name=uid,proto3" json:"uid,omitempty"` // 玩家的唯一id
	Name       string  `protobuf:"bytes,13,opt,name=name,proto3" json:"name,omitempty"`
	SkinId     uint32  `protobuf:"varint,14,opt,name=skinId,proto3" json:"skinId,omitempty"` // 皮肤id
	Color      *Color  `protobuf:"bytes,15,opt,name=color,proto3" json:"color,omitempty"`    // 颜色
}

func (x *Ball) Reset() {
	*x = Ball{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logicuser_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ball) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ball) ProtoMessage() {}

func (x *Ball) ProtoReflect() protoreflect.Message {
	mi := &file_logicuser_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ball.ProtoReflect.Descriptor instead.
func (*Ball) Descriptor() ([]byte, []int) {
	return file_logicuser_proto_rawDescGZIP(), []int{10}
}

func (x *Ball) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Ball) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Ball) GetNx() float32 {
	if x != nil {
		return x.Nx
	}
	return 0
}

func (x *Ball) GetNy() float32 {
	if x != nil {
		return x.Ny
	}
	return 0
}

func (x *Ball) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Ball) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Ball) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Ball) GetMoveX() float32 {
	if x != nil {
		return x.MoveX
	}
	return 0
}

func (x *Ball) GetMoveY() float32 {
	if x != nil {
		return x.MoveY
	}
	return 0
}

func (x *Ball) GetMoveS() float32 {
	if x != nil {
		return x.MoveS
	}
	return 0
}

func (x *Ball) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *Ball) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *Ball) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Ball) GetSkinId() uint32 {
	if x != nil {
		return x.SkinId
	}
	return 0
}

func (x *Ball) GetColor() *Color {
	if x != nil {
		return x.Color
	}
	return nil
}

type CameraPos struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X       float32 `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y       float32 `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Nx      float32 `protobuf:"fixed32,3,opt,name=nx,proto3" json:"nx,omitempty"`
	Ny      float32 `protobuf:"fixed32,4,opt,name=ny,proto3" json:"ny,omitempty"`
	Sx      float32 `protobuf:"fixed32,5,opt,name=sx,proto3" json:"sx,omitempty"`
	Sy      float32 `protobuf:"fixed32,6,opt,name=sy,proto3" json:"sy,omitempty"`
	Nsx     float32 `protobuf:"fixed32,7,opt,name=nsx,proto3" json:"nsx,omitempty"`
	Nsy     float32 `protobuf:"fixed32,8,opt,name=nsy,proto3" json:"nsy,omitempty"`
	Score   float32 `protobuf:"fixed32,9,opt,name=score,proto3" json:"score,omitempty"` //当前玩家分数
	Id      uint32  `protobuf:"varint,10,opt,name=id,proto3" json:"id,omitempty"`       // 主球id
	Curtime int64   `protobuf:"varint,11,opt,name=curtime,proto3" json:"curtime,omitempty"`
}

func (x *CameraPos) Reset() {
	*x = CameraPos{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logicuser_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CameraPos) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CameraPos) ProtoMessage() {}

func (x *CameraPos) ProtoReflect() protoreflect.Message {
	mi := &file_logicuser_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CameraPos.ProtoReflect.Descriptor instead.
func (*CameraPos) Descriptor() ([]byte, []int) {
	return file_logicuser_proto_rawDescGZIP(), []int{11}
}

func (x *CameraPos) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *CameraPos) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *CameraPos) GetNx() float32 {
	if x != nil {
		return x.Nx
	}
	return 0
}

func (x *CameraPos) GetNy() float32 {
	if x != nil {
		return x.Ny
	}
	return 0
}

func (x *CameraPos) GetSx() float32 {
	if x != nil {
		return x.Sx
	}
	return 0
}

func (x *CameraPos) GetSy() float32 {
	if x != nil {
		return x.Sy
	}
	return 0
}

func (x *CameraPos) GetNsx() float32 {
	if x != nil {
		return x.Nsx
	}
	return 0
}

func (x *CameraPos) GetNsy() float32 {
	if x != nil {
		return x.Nsy
	}
	return 0
}

func (x *CameraPos) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *CameraPos) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CameraPos) GetCurtime() int64 {
	if x != nil {
		return x.Curtime
	}
	return 0
}

type Coordinate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X float32 `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y float32 `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Z float32 `protobuf:"fixed32,3,opt,name=z,proto3" json:"z,omitempty"`
}

func (x *Coordinate) Reset() {
	*x = Coordinate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logicuser_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Coordinate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Coordinate) ProtoMessage() {}

func (x *Coordinate) ProtoReflect() protoreflect.Message {
	mi := &file_logicuser_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Coordinate.ProtoReflect.Descriptor instead.
func (*Coordinate) Descriptor() ([]byte, []int) {
	return file_logicuser_proto_rawDescGZIP(), []int{12}
}

func (x *Coordinate) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Coordinate) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Coordinate) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

type Pair struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key  uint64  `protobuf:"varint,1,opt,name=key,proto3" json:"key,omitempty"`
	Name string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Val  float32 `protobuf:"fixed32,3,opt,name=val,proto3" json:"val,omitempty"`
}

func (x *Pair) Reset() {
	*x = Pair{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logicuser_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pair) ProtoMessage() {}

func (x *Pair) ProtoReflect() protoreflect.Message {
	mi := &file_logicuser_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pair.ProtoReflect.Descriptor instead.
func (*Pair) Descriptor() ([]byte, []int) {
	return file_logicuser_proto_rawDescGZIP(), []int{13}
}

func (x *Pair) GetKey() uint64 {
	if x != nil {
		return x.Key
	}
	return 0
}

func (x *Pair) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Pair) GetVal() float32 {
	if x != nil {
		return x.Val
	}
	return 0
}

type Color struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	R uint32 `protobuf:"varint,1,opt,name=r,proto3" json:"r,omitempty"`
	G uint32 `protobuf:"varint,2,opt,name=g,proto3" json:"g,omitempty"`
	B uint32 `protobuf:"varint,3,opt,name=b,proto3" json:"b,omitempty"`
	A uint32 `protobuf:"varint,4,opt,name=a,proto3" json:"a,omitempty"`
}

func (x *Color) Reset() {
	*x = Color{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logicuser_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Color) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Color) ProtoMessage() {}

func (x *Color) ProtoReflect() protoreflect.Message {
	mi := &file_logicuser_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Color.ProtoReflect.Descriptor instead.
func (*Color) Descriptor() ([]byte, []int) {
	return file_logicuser_proto_rawDescGZIP(), []int{14}
}

func (x *Color) GetR() uint32 {
	if x != nil {
		return x.R
	}
	return 0
}

func (x *Color) GetG() uint32 {
	if x != nil {
		return x.G
	}
	return 0
}

func (x *Color) GetB() uint32 {
	if x != nil {
		return x.B
	}
	return 0
}

func (x *Color) GetA() uint32 {
	if x != nil {
		return x.A
	}
	return 0
}

type Top struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MyTop int32   `protobuf:"varint,1,opt,name=myTop,proto3" json:"myTop,omitempty"`
	Pair  []*Pair `protobuf:"bytes,2,rep,name=pair,proto3" json:"pair,omitempty"`
}

func (x *Top) Reset() {
	*x = Top{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logicuser_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Top) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Top) ProtoMessage() {}

func (x *Top) ProtoReflect() protoreflect.Message {
	mi := &file_logicuser_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Top.ProtoReflect.Descriptor instead.
func (*Top) Descriptor() ([]byte, []int) {
	return file_logicuser_proto_rawDescGZIP(), []int{15}
}

func (x *Top) GetMyTop() int32 {
	if x != nil {
		return x.MyTop
	}
	return 0
}

func (x *Top) GetPair() []*Pair {
	if x != nil {
		return x.Pair
	}
	return nil
}

type UserList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Num      uint32  `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
	UserList []*User `protobuf:"bytes,2,rep,name=userList,proto3" json:"userList,omitempty"`
}

func (x *UserList) Reset() {
	*x = UserList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logicuser_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserList) ProtoMessage() {}

func (x *UserList) ProtoReflect() protoreflect.Message {
	mi := &file_logicuser_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserList.ProtoReflect.Descriptor instead.
func (*UserList) Descriptor() ([]byte, []int) {
	return file_logicuser_proto_rawDescGZIP(), []int{16}
}

func (x *UserList) GetNum() uint32 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *UserList) GetUserList() []*User {
	if x != nil {
		return x.UserList
	}
	return nil
}

type RoomList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomList []*Room `protobuf:"bytes,1,rep,name=roomList,proto3" json:"roomList,omitempty"`
}

func (x *RoomList) Reset() {
	*x = RoomList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logicuser_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomList) ProtoMessage() {}

func (x *RoomList) ProtoReflect() protoreflect.Message {
	mi := &file_logicuser_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomList.ProtoReflect.Descriptor instead.
func (*RoomList) Descriptor() ([]byte, []int) {
	return file_logicuser_proto_rawDescGZIP(), []int{17}
}

func (x *RoomList) GetRoomList() []*Room {
	if x != nil {
		return x.RoomList
	}
	return nil
}

type Res struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int32  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Msg    string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *Res) Reset() {
	*x = Res{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logicuser_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Res) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Res) ProtoMessage() {}

func (x *Res) ProtoReflect() protoreflect.Message {
	mi := &file_logicuser_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Res.ProtoReflect.Descriptor instead.
func (*Res) Descriptor() ([]byte, []int) {
	return file_logicuser_proto_rawDescGZIP(), []int{18}
}

func (x *Res) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Res) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_logicuser_proto protoreflect.FileDescriptor

var file_logicuser_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0a, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x9f, 0x01,
	0x0a, 0x04, 0x55, 0x73, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x61,
	0x73, 0x73, 0x77, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x61, 0x73, 0x73,
	0x77, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x50, 0x61, 0x73, 0x73, 0x77, 0x64, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x50, 0x61, 0x73, 0x73, 0x77, 0x64, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x6b, 0x69, 0x6e, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06,
	0x73, 0x6b, 0x69, 0x6e, 0x49, 0x64, 0x12, 0x27, 0x0a, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x52, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x22,
	0x7a, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x1e, 0x0a, 0x0a, 0x65,
	0x78, 0x70, 0x65, 0x72, 0x69, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0a, 0x65, 0x78, 0x70, 0x65, 0x72, 0x69, 0x65, 0x6e, 0x63, 0x65, 0x22, 0xab, 0x01, 0x0a, 0x08,
	0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x6f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x6f, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x24, 0x0a, 0x04, 0x75, 0x73,
	0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x63,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72,
	0x12, 0x24, 0x0a, 0x04, 0x72, 0x6f, 0x6f, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10,
	0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x6f, 0x6f, 0x6d,
	0x52, 0x04, 0x72, 0x6f, 0x6f, 0x6d, 0x12, 0x21, 0x0a, 0x03, 0x61, 0x63, 0x74, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x41, 0x63, 0x74, 0x52, 0x03, 0x61, 0x63, 0x74, 0x22, 0x43, 0x0a, 0x0b, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x70, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x6f, 0x70, 0x12, 0x24, 0x0a, 0x04, 0x72, 0x6f, 0x6f, 0x6d,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x04, 0x72, 0x6f, 0x6f, 0x6d, 0x22, 0x5e,
	0x0a, 0x0c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x24, 0x0a, 0x04, 0x72, 0x6f, 0x6f, 0x6d,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x04, 0x72, 0x6f, 0x6f, 0x6d, 0x22, 0xba,
	0x01, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x30, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x69, 0x6e, 0x66,
	0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x75,
	0x73, 0x65, 0x72, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x24, 0x0a, 0x04, 0x72, 0x6f, 0x6f, 0x6d, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x04, 0x72, 0x6f, 0x6f, 0x6d, 0x12, 0x2c, 0x0a,
	0x08, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x73, 0x65,
	0x72, 0x52, 0x08, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x9e, 0x01, 0x0a, 0x0c,
	0x49, 0x6e, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x28, 0x0a, 0x06, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6c, 0x6f, 0x67,
	0x69, 0x63, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x61, 0x6c, 0x6c, 0x52, 0x06, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x12, 0x26, 0x0a, 0x05, 0x71, 0x75, 0x61, 0x72, 0x6b, 0x18, 0x05, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x42, 0x61, 0x6c, 0x6c, 0x52, 0x05, 0x71, 0x75, 0x61, 0x72, 0x6b, 0x22, 0xb2, 0x02, 0x0a,
	0x0e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x2a, 0x0a, 0x07, 0x70, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6c, 0x6f, 0x67,
	0x69, 0x63, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x61, 0x6c, 0x6c, 0x52, 0x07, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x73, 0x12, 0x26, 0x0a, 0x05, 0x66, 0x6f, 0x6f, 0x64, 0x73, 0x18, 0x04,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x42, 0x61, 0x6c, 0x6c, 0x52, 0x05, 0x66, 0x6f, 0x6f, 0x64, 0x73, 0x12, 0x26, 0x0a,
	0x05, 0x73, 0x70, 0x6f, 0x72, 0x65, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6c,
	0x6f, 0x67, 0x69, 0x63, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x61, 0x6c, 0x6c, 0x52, 0x05,
	0x73, 0x70, 0x6f, 0x72, 0x65, 0x12, 0x2d, 0x0a, 0x06, 0x63, 0x61, 0x6d, 0x50, 0x6f, 0x73, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x43, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x50, 0x6f, 0x73, 0x52, 0x06, 0x63, 0x61,
	0x6d, 0x50, 0x6f, 0x73, 0x12, 0x28, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x21,
	0x0a, 0x03, 0x74, 0x6f, 0x70, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6c, 0x6f,
	0x67, 0x69, 0x63, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x6f, 0x70, 0x52, 0x03, 0x74, 0x6f,
	0x70, 0x22, 0xf4, 0x01, 0x0a, 0x04, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x64,
	0x64, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x64, 0x64, 0x72, 0x12, 0x18,
	0x0a, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x4e, 0x75, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x07, 0x70, 0x6c, 0x61, 0x79, 0x4e, 0x75, 0x6d, 0x12, 0x18, 0x0a, 0x07, 0x77, 0x61, 0x69, 0x74,
	0x4e, 0x75, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x77, 0x61, 0x69, 0x74, 0x4e,
	0x75, 0x6d, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x4e, 0x75, 0x6d, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x4e, 0x75, 0x6d, 0x12, 0x1c,
	0x0a, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x07, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x77, 0x69, 0x64,
	0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x2c, 0x0a, 0x08, 0x75, 0x73,
	0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x09, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6c,
	0x6f, 0x67, 0x69, 0x63, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x08,
	0x75, 0x73, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x5b, 0x0a, 0x03, 0x41, 0x63, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x76, 0x65, 0x58, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x05, 0x6d, 0x6f, 0x76, 0x65, 0x58, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x76,
	0x65, 0x59, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x6d, 0x6f, 0x76, 0x65, 0x59, 0x12,
	0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x76, 0x65, 0x53, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05,
	0x6d, 0x6f, 0x76, 0x65, 0x53, 0x22, 0xc5, 0x02, 0x0a, 0x04, 0x42, 0x61, 0x6c, 0x6c, 0x12, 0x0c,
	0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01,
	0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x6e, 0x78,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x02, 0x6e, 0x78, 0x12, 0x0e, 0x0a, 0x02, 0x6e, 0x79,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x02, 0x6e, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63,
	0x6f, 0x72, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x76, 0x65, 0x58, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x05, 0x6d, 0x6f, 0x76, 0x65, 0x58, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f,
	0x76, 0x65, 0x59, 0x18, 0x09, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x6d, 0x6f, 0x76, 0x65, 0x59,
	0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x76, 0x65, 0x53, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x05, 0x6d, 0x6f, 0x76, 0x65, 0x53, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x54, 0x69, 0x6d, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x0c, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x6b, 0x69, 0x6e, 0x49, 0x64, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x73, 0x6b,
	0x69, 0x6e, 0x49, 0x64, 0x12, 0x27, 0x0a, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x0f, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x52, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x22, 0xcb, 0x01,
	0x0a, 0x09, 0x43, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x50, 0x6f, 0x73, 0x12, 0x0c, 0x0a, 0x01, 0x78,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x6e, 0x78, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x02, 0x6e, 0x78, 0x12, 0x0e, 0x0a, 0x02, 0x6e, 0x79, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x02, 0x6e, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x73, 0x78, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x02, 0x73, 0x78, 0x12, 0x0e, 0x0a, 0x02, 0x73, 0x79, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x02, 0x73, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x73, 0x78, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x6e, 0x73, 0x78, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x73, 0x79,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x6e, 0x73, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x73,
	0x63, 0x6f, 0x72, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x72,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x75, 0x72, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x0b, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x07, 0x63, 0x75, 0x72, 0x74, 0x69, 0x6d, 0x65, 0x22, 0x36, 0x0a, 0x0a, 0x43,
	0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x01, 0x79, 0x12, 0x0c, 0x0a, 0x01, 0x7a, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x01, 0x7a, 0x22, 0x3e, 0x0a, 0x04, 0x50, 0x61, 0x69, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x76, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03,
	0x76, 0x61, 0x6c, 0x22, 0x3f, 0x0a, 0x05, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x12, 0x0c, 0x0a, 0x01,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x01, 0x72, 0x12, 0x0c, 0x0a, 0x01, 0x67, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x01, 0x67, 0x12, 0x0c, 0x0a, 0x01, 0x62, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x01, 0x62, 0x12, 0x0c, 0x0a, 0x01, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x01, 0x61, 0x22, 0x41, 0x0a, 0x03, 0x54, 0x6f, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x6d,
	0x79, 0x54, 0x6f, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6d, 0x79, 0x54, 0x6f,
	0x70, 0x12, 0x24, 0x0a, 0x04, 0x70, 0x61, 0x69, 0x72, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x61, 0x69,
	0x72, 0x52, 0x04, 0x70, 0x61, 0x69, 0x72, 0x22, 0x4a, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x4c,
	0x69, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x03, 0x6e, 0x75, 0x6d, 0x12, 0x2c, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4c, 0x69, 0x73,
	0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4c,
	0x69, 0x73, 0x74, 0x22, 0x38, 0x0a, 0x08, 0x52, 0x6f, 0x6f, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x12,
	0x2c, 0x0a, 0x08, 0x72, 0x6f, 0x6f, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x10, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52,
	0x6f, 0x6f, 0x6d, 0x52, 0x08, 0x72, 0x6f, 0x6f, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x2f, 0x0a,
	0x03, 0x52, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x10, 0x0a, 0x03,
	0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x32, 0x72,
	0x0a, 0x04, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x33, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x6f,
	0x6d, 0x12, 0x14, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55,
	0x73, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x22, 0x00, 0x12, 0x35, 0x0a, 0x0a, 0x4e,
	0x6f, 0x74, 0x69, 0x66, 0x79, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x14, 0x2e, 0x6c, 0x6f, 0x67, 0x69,
	0x63, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x1a,
	0x0f, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x73,
	0x22, 0x00, 0x42, 0x0e, 0x5a, 0x0c, 0x2e, 0x2f, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_logicuser_proto_rawDescOnce sync.Once
	file_logicuser_proto_rawDescData = file_logicuser_proto_rawDesc
)

func file_logicuser_proto_rawDescGZIP() []byte {
	file_logicuser_proto_rawDescOnce.Do(func() {
		file_logicuser_proto_rawDescData = protoimpl.X.CompressGZIP(file_logicuser_proto_rawDescData)
	})
	return file_logicuser_proto_rawDescData
}

var file_logicuser_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_logicuser_proto_goTypes = []interface{}{
	(*User)(nil),           // 0: logicProto.User
	(*UserInfo)(nil),       // 1: logicProto.UserInfo
	(*Operator)(nil),       // 2: logicProto.Operator
	(*RequestRoom)(nil),    // 3: logicProto.RequestRoom
	(*ResponseRoom)(nil),   // 4: logicProto.ResponseRoom
	(*Response)(nil),       // 5: logicProto.Response
	(*InitResponse)(nil),   // 6: logicProto.InitResponse
	(*UpdateResponse)(nil), // 7: logicProto.UpdateResponse
	(*Room)(nil),           // 8: logicProto.Room
	(*Act)(nil),            // 9: logicProto.Act
	(*Ball)(nil),           // 10: logicProto.Ball
	(*CameraPos)(nil),      // 11: logicProto.CameraPos
	(*Coordinate)(nil),     // 12: logicProto.Coordinate
	(*Pair)(nil),           // 13: logicProto.Pair
	(*Color)(nil),          // 14: logicProto.Color
	(*Top)(nil),            // 15: logicProto.Top
	(*UserList)(nil),       // 16: logicProto.UserList
	(*RoomList)(nil),       // 17: logicProto.RoomList
	(*Res)(nil),            // 18: logicProto.Res
}
var file_logicuser_proto_depIdxs = []int32{
	14, // 0: logicProto.User.color:type_name -> logicProto.Color
	0,  // 1: logicProto.Operator.user:type_name -> logicProto.User
	8,  // 2: logicProto.Operator.room:type_name -> logicProto.Room
	9,  // 3: logicProto.Operator.act:type_name -> logicProto.Act
	8,  // 4: logicProto.RequestRoom.room:type_name -> logicProto.Room
	8,  // 5: logicProto.ResponseRoom.room:type_name -> logicProto.Room
	1,  // 6: logicProto.Response.userinfo:type_name -> logicProto.UserInfo
	8,  // 7: logicProto.Response.room:type_name -> logicProto.Room
	0,  // 8: logicProto.Response.UserList:type_name -> logicProto.User
	10, // 9: logicProto.InitResponse.player:type_name -> logicProto.Ball
	10, // 10: logicProto.InitResponse.quark:type_name -> logicProto.Ball
	10, // 11: logicProto.UpdateResponse.players:type_name -> logicProto.Ball
	10, // 12: logicProto.UpdateResponse.foods:type_name -> logicProto.Ball
	10, // 13: logicProto.UpdateResponse.spore:type_name -> logicProto.Ball
	11, // 14: logicProto.UpdateResponse.camPos:type_name -> logicProto.CameraPos
	1,  // 15: logicProto.UpdateResponse.user:type_name -> logicProto.UserInfo
	15, // 16: logicProto.UpdateResponse.top:type_name -> logicProto.Top
	0,  // 17: logicProto.Room.userList:type_name -> logicProto.User
	14, // 18: logicProto.Ball.color:type_name -> logicProto.Color
	13, // 19: logicProto.Top.pair:type_name -> logicProto.Pair
	0,  // 20: logicProto.UserList.userList:type_name -> logicProto.User
	8,  // 21: logicProto.RoomList.roomList:type_name -> logicProto.Room
	16, // 22: logicProto.Meta.GetRoom:input_type -> logicProto.UserList
	17, // 23: logicProto.Meta.NotifyRoom:input_type -> logicProto.RoomList
	8,  // 24: logicProto.Meta.GetRoom:output_type -> logicProto.Room
	18, // 25: logicProto.Meta.NotifyRoom:output_type -> logicProto.Res
	24, // [24:26] is the sub-list for method output_type
	22, // [22:24] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_logicuser_proto_init() }
func file_logicuser_proto_init() {
	if File_logicuser_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_logicuser_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*User); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logicuser_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logicuser_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Operator); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logicuser_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestRoom); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logicuser_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseRoom); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logicuser_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logicuser_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logicuser_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logicuser_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Room); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logicuser_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Act); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logicuser_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ball); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logicuser_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CameraPos); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logicuser_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Coordinate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logicuser_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pair); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logicuser_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Color); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logicuser_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Top); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logicuser_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logicuser_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logicuser_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Res); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_logicuser_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_logicuser_proto_goTypes,
		DependencyIndexes: file_logicuser_proto_depIdxs,
		MessageInfos:      file_logicuser_proto_msgTypes,
	}.Build()
	File_logicuser_proto = out.File
	file_logicuser_proto_rawDesc = nil
	file_logicuser_proto_goTypes = nil
	file_logicuser_proto_depIdxs = nil
}
